version: '3'

services:
  users-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - users-postgres

  users-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
